#!/usr/bin/python


import sys
import numpy as np
from guess import recognize
from guess import convert
from library import *
import cv2
import json

if len(sys.argv) != 2:
    print '\n Usage: python ./parse <path to captcha image>\n'
    sys.exit(0)

filename = sys.argv[1]

#######   training part    ###############
samples = np.loadtxt('generalsamples.data', np.float32)
responses = np.loadtxt('generalresponses.data', np.float32)
responses = responses.reshape((responses.size, 1))

model = cv2.KNearest()
model.train(samples, responses)

try:
    with open('cache.txt', 'r') as f:
        cache = json.loads(f.read()) or {}
except Exception, e:
    cache = {}

orig, result = recognize(filename)
if result:
    print convert(result)
else:
    print "false"
